/**
 * Cloudflare D1 adapter for the sqlitekit `SqliteDriver` contract.
 *
 * D1 is Cloudflare's hosted SQLite service: a SQLite engine running
 * inside their edge network, accessed from a Worker via the binding
 * object you wire in `wrangler.toml`. It speaks SQL but its
 * connection model is HTTP-based, which means a few things differ
 * from a local SQLite:
 *
 *   - **No multi-statement transactions across requests.** `BEGIN /
 *     COMMIT` only works inside a single `db.batch([...])` call.
 *     Sequential `await db.run(...)` calls between BEGIN and COMMIT
 *     don't share a transaction — each call is its own HTTP round-trip.
 *
 *   - **Async-everywhere.** Every D1 call returns a Promise, naturally
 *     fitting the async `SqliteDriver` contract (no `Promise.resolve()`
 *     wrapping like better-sqlite3 needs).
 *
 *   - **Result shape differs.** `.run()` returns
 *     `{ success, meta: { changes, last_row_id, ... } }`; `.all()`
 *     returns `{ results: T[], success, meta }`. The adapter maps
 *     these onto sqlitekit's normalized shapes.
 *
 *   - **No filesystem.** `fromDrizzleDir` (which reads SQL files at
 *     runtime) doesn't work in Workers. Use `wrangler d1 migrations`
 *     for the migration story; this adapter only handles the runtime
 *     CRUD path.
 *
 * For the repository layer, callers wire the Drizzle D1 db directly:
 *
 * ```ts
 * import { drizzle } from 'drizzle-orm/d1';
 * import { SqliteRepository } from '@classytic/sqlitekit/repository';
 *
 * export default {
 *   async fetch(req, env) {
 *     const db = drizzle(env.DB);
 *     const repo = new SqliteRepository({ db, table: usersTable });
 *     // ... same .create / .findAll / .updateMany as Node
 *   },
 * };
 * ```
 *
 * This `createD1Driver` is for the rare paths that need raw SQL (the
 * sqlitekit migrator, custom DDL via `driver.exec`). Drizzle handles
 * everything else.
 */

import type { SqliteDriver, SqliteRunResult, SqliteStatement } from './types.js';

/**
 * Minimal structural type for a Cloudflare D1 database binding. We
 * deliberately don't depend on `@cloudflare/workers-types` so this
 * file imports cleanly in Node test environments — the only runtime
 * requirement is that the object passed in implements these methods.
 */
export interface D1DatabaseLike {
  prepare(sql: string): D1PreparedStatementLike;
  exec(sql: string): Promise<unknown>;
  batch(statements: D1PreparedStatementLike[]): Promise<unknown>;
}

/** Prepared-statement shape D1 returns from `db.prepare(sql)`. */
export interface D1PreparedStatementLike {
  bind(...values: unknown[]): D1PreparedStatementLike;
  first<T = unknown>(): Promise<T | null>;
  all<T = unknown>(): Promise<{ results: T[]; success: boolean; meta?: unknown }>;
  run(): Promise<{ success: boolean; meta: { changes?: number; last_row_id?: number } }>;
}

/**
 * Wrap a D1 binding in the `SqliteDriver` contract. The binding is
 * the `env.DB` (or whatever name your wrangler.toml gave it) inside a
 * Worker handler.
 *
 * Transactions: throws clearly. D1 doesn't support cross-request
 * transactions; use `db.batch([stmt1, stmt2])` directly via the
 * Drizzle d1 db, or restructure the operation to fit a single batch.
 */
export function createD1Driver(d1: D1DatabaseLike): SqliteDriver {
  const driver: SqliteDriver = {
    async run(stmt: SqliteStatement): Promise<SqliteRunResult> {
      const prepared = d1.prepare(stmt.sql).bind(...(stmt.params as unknown[]));
      const result = await prepared.run();
      return {
        changes: result.meta.changes ?? 0,
        // D1's `last_row_id` is a number; sqlitekit's contract permits
        // `number | bigint` so we widen here.
        lastInsertRowid: result.meta.last_row_id ?? 0,
      };
    },
    async all<TRow = Record<string, unknown>>(stmt: SqliteStatement): Promise<TRow[]> {
      const prepared = d1.prepare(stmt.sql).bind(...(stmt.params as unknown[]));
      const result = await prepared.all<TRow>();
      return result.results;
    },
    async get<TRow = Record<string, unknown>>(stmt: SqliteStatement): Promise<TRow | undefined> {
      const prepared = d1.prepare(stmt.sql).bind(...(stmt.params as unknown[]));
      const row = await prepared.first<TRow>();
      return row ?? undefined;
    },
    async exec(sql: string): Promise<void> {
      // D1's `exec()` accepts multi-statement SQL but each statement
      // must be terminated by a newline (per Cloudflare docs). For DDL
      // generated by drizzle-kit this is the case; for hand-written
      // multi-statement SQL the caller should ensure newline termination.
      await d1.exec(sql);
    },
    transaction(): never {
      throw new Error(
        'sqlitekit/driver/d1: transactions are not supported on Cloudflare D1. ' +
          'Use `db.batch([stmt1, stmt2, ...])` for atomic multi-statement execution, ' +
          'or restructure the operation to a single statement.',
      );
    },
  };
  return driver;
}
